-- lua/config/autocmds.lua

local function rgb_to_hex(rgb)
  return rgb and string.format("#%06x", rgb) or nil
end

vim.api.nvim_create_autocmd("ColorScheme", {
  pattern = "*",
  -- Pass 'args' into the function to trap the exact event data
  callback = function(args)
    -- Use args.match to get exactly what was typed (e.g., "cobaltnext")
    local theme = args.match or vim.g.colors_name or ""
    if theme == "" then
      return
    end

    local cache_file = vim.fn.expand("~/.cache/nvim_theme")
    local f = io.open(cache_file, "w")
    if f then
      f:write(theme)
      f:close()
    end

    local normal = vim.api.nvim_get_hl(0, { name = "Normal", link = false })
    local fg = rgb_to_hex(normal.fg) or "#c0caf5"
    local bg = rgb_to_hex(normal.bg)

    if not bg then
      -- Differentiate between the two Cobalt variants if background is transparent
      if theme == "cobaltnext_dark" then
        bg = "#0f1c23"
      elseif theme == "cobaltnext" then
        bg = "#1b2b34"
      elseif theme:match("kanagawa") then
        bg = "#1F1F28"
      elseif theme:match("catppuccin") then
        bg = "#1E1E2E"
      elseif theme:match("rose%-pine") then
        bg = "#191724"
      elseif theme:match("gruvbox") then
        bg = "#282828"
      elseif theme:match("everforest") then
        bg = "#2D353B"
      else
        bg = vim.g.terminal_color_0 or "#1a1b26"
      end
    end

    local kitty_conf = {
      "# This file is auto-generated by Neovim",
      "foreground " .. fg,
      "background " .. bg,
      "selection_background " .. fg,
      "selection_foreground " .. bg,
    }

    -- Grab all 16 terminal colors defined by the theme
    for i = 0, 15 do
      local col = vim.g["terminal_color_" .. i]
      if col then
        table.insert(kitty_conf, "color" .. i .. " " .. col)
      end
    end

    local kitty_export_path = vim.fn.expand("~/.config/kitty/nvim_export.conf")
    local kf = io.open(kitty_export_path, "w")
    if kf then
      kf:write(table.concat(kitty_conf, "\n"))
      kf:close()
    end

    vim.fn.jobstart("kitty @ set-colors -a " .. kitty_export_path)
  end,
})
